### ISSUE TITLE
After installation the Javascript Snippet Pack is not available

### ISSUE THREAD

**Issue by CJHarmath** [madskristensen/WebExtensionPack#5] opened 2016-03-24 21:30 UTC
### Installed product versions
- Visual Studio: 2015 Professional Update 1
- Web Extension Pack version: 1.2.35
### Description

After successful installation of vsix, the Javascript Snippet Pack is missing from snippet manager, but it's there at the installed extensions.
If you uninstall the Javasript snippet pack extension, then VS will restart then install it back and the snippet will also show up.
But even after that the snippets are actually not working as shown on the animated gif at the extension's page
### Steps to recreate
1. install the extension
2. check Code Snippet Manager if the Javascript snippet pack is there 
3. if not, remove the Javascript Snippet extension
4. check if it fixes it
5. check if the js pack snippets are working
### Current behavior

Even after the workaround to install the js snippet pack snippets are not working.
### Expected behavior

Installation should work without work around and the javascript snippets shall work

**Comment by madskristensen** [comment] 2016-03-24 21:58
I cannot reproduce this issue. It sounds like something in the VS snippet registration system is broken. Can you try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd and see if it helps?

**Comment by CJHarmath** [comment] 2016-03-25 02:17
We were able to reproduce on multiple desktops. All Windows 7, which I forgot to include.
Will check the Clear MEF Cache and report back...

**Comment by CJHarmath** [comment] 2016-03-25 02:51
I was able to reproduce it on another box with Windows 10 / VS 2015 update 1 as well.
After installing the Web Extension Pack the JS snippet pack wasn't in the snippets but showed up as an installed extension.
Cleaning MEF Cache didn't fix it.
Uninstalling JavaScript Snippet Pack from the Extensions triggers VS restart which then on startup starts with installing it back then asking to restart again.
Then after this it works fine.

**Comment by CJHarmath** [comment] 2016-04-08 17:46
@madskristensen  i wonder if you were able to reproduce it ?
Am I the only one who had this ?

thanks

**Comment by madskristensen** [comment] 2016-06-28 15:36
This is now fixed so you can uninstall any extension and Web Extension Pack doesn't just reinstall it immediately after a restart

**Closed as completed by madskristensen** 2016-06-28 15:36 UTC

**Comment by CJHarmath** [comment] 2016-06-29 01:15
thanks @madskristensen
