### ISSUE TITLE
Alway reinstall Glyphfriend with every start of Visual Studio 

### ISSUE THREAD

**Issue by rheid** [madskristensen/WebExtensionPack#13] opened 2016-11-17 18:26 UTC
## Suggest an extension:
Add the name and a link to the VS Gallery download page.

...or report a bug:

### Installed product versions
- Visual Studio: 2015 Enterprise 

### Description
Alway reinstall Glyphfriend with every start of Visual Studio 
![rg sp2016dev01 2016-11-17 19-26-29](https://cloud.githubusercontent.com/assets/1476336/20402119/c28d0510-acfb-11e6-8195-c7d30d14180a.png)

### Steps to recreate
1. Install WebExtensionPack
2. Restart Visual Studio 
3. Alway ask for Restart Web Extension Pack Glyphfriend

### Current behavior
Only Install on Time

### Expected behavior
Alway Install extensions

**Comment by nicholashead** [comment] 2016-11-17 21:29
This is a dupe of #12

**Closed as completed** 2016-11-17 21:38 UTC
